[package]
name = "minidht"
version = "0.1.0"
edition = "2018"
authors = ["Ian Kim <ian@ianmkim.com>"]

[dependencies]
rustc-serialize = "0.3.*"
rand = "0.8.*"
rust-crypto = "0.2.*"
log = "0.4.*"
env_logger = "0.9.*"
